export enum ImageSource {
    AVATAR = 'avatar',
    PROFILE_DOCS = 'profile_docs',
    BLOGS = 'blogs',
    WEBINARS = 'webinars',
    PROJECT = 'projects',
    CONFERENCES = 'conferences',
    PROGRAMME = 'programme',
    COURSE = 'course',
    AUTHOR = 'author',
    MENTORPERKS = 'mentorperks',    
    COLLEGEYOPPORTUNITY = 'collegeyopportunities',
    TEAM_MEMBER='team_member',
    LOGO = 'logo',
    COLLEGE_LOGO = 'college_logo',
    UNIVERSITY_LOGO = 'university_logo',
    BADGE = 'badge',
    COLLEGYFEED='postImageUrl',
}